import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FaMoon, FaLinkedin, FaGithub, FaYoutube } from 'react-icons/fa'
import profile from '../public/profile.png'
import computer from '../public/computer.png'
import book from '../public/book.png'
import thumb from '../public/thumb.png'
import Slideshow from '../comps/slideshow'

import { useState, useEffect } from 'react'


export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title className=''>Logan Robitaille's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white  font-Oxygen'>
        <section className=" min-h-screen px-10 md:px-20 lg:px-40">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-lg text-gray-800 dark:text-white'>Logan Robitaille</h1>
            <ul className='flex items-center gap-4'>
              {/* <li className='cursor-pointer text-2xl text-gray-800'><FaMoon className='text-gray-800 dark:text-white' onClick={() => { setDarkMode(!darkMode); console.log(darkMode) }} /></li> */}
              <li><a className='bg-gradient-to-tr from-rose-700 to-violet-500 text-white px-6 py-2 rounded-md lm-8 dark:from-rose-500to-violet-200 text-md hover:bg-white' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='flex mx-auto my-5 relative bg-gradient-to-r from-rose-700 to-violet-500 rounded-full w-60 h-60 border-2 border-white'>

          </div>
          <div className='text-center p-10'>
            <h2 className="text-3xl font-semibold py-2 text-transparent 
            bg-clip-text bg-gradient-to-b from-rose-700 to-violet-500 md:text-4xl lg:text-5xl ">Logan Robitaille</h2>
            <h3 className="text-md font-semibold py-2 text-rose-700 md:text-xl lg:text-2xl ">Fullstack Junior Developer</h3>
            <p className="text-md pt-2 leading-8 text-gray-800 lg:text-lg dark:text-white">
              Self-taught fullstack web developer specializing in frontend development.
            </p>
            <p className="text-md mx-auto pb-2 leading-8 text-gray-800 lg:text-lg dark:text-gray-100">
              Well-versed in JavaScript, React.js, Next.js, HTML, CSS, Tailwind CSS, Node.js & Express.js
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 pb-10 text-gray-800 lg:pb-16 dark:text-gray-100'>
            <a><FaLinkedin /></a>
            <a><FaGithub /></a>
          </div>
        </section>
        <section className='px-10 md:px-20 pb-7 lg:px-40 bg-gradient-to-br from-rose-50 to-white '>
          <div className='flex flex-col justify-center'>
            <h3 className='text-2xl py-5 font-semibold text-transparent 
          bg-clip-text bg-gradient-to-b from-rose-700 to-violet-500 flex justify-center md:text-3xl lg:text-4xl'>What I bring to the table</h3>
            <p className='text-md py-2 pb-5 leading-8 text-gray-800 text-center lg:text-lg'>
              I've completed <a className='text-rose-400' href='https://www.theodinproject.com/paths/full-stack-javascript?'>The Odin Project Curriculum</a>, which has given me <strong>3</strong> main skills that bring value.
            </p>
          </div>
          <div className='lg:flex flex-row gap-5 justify-center'>
            <div className='mb-5 text-center shadow-xl p-10 rounded-lg w-100 lg:text-lg lg:px-15 bg-white lg:w-1/3'>
              <Image src={computer} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-semibold py-2 text-rose-700 lg:text-xl'>Modern Frontend Development</h3>
              <p className='py-2 leading-8 text-gray-800'>As you can see with this web page, I know how to give a website a simple, yet modern feel.</p>
              <h4 className="text-md font-semibold py-2 text-rose-700">What I Use</h4>
              <p className='text-gray-800 py-1'>Next.js & React</p>
              <p className='text-gray-800 py-1'>Tailwind CSS</p>
              <p className='text-gray-800 py-1'> Many other libraries </p>
            </div>
            <div className='mb-5 text-center shadow-xl p-10 rounded-lg lg:text-lg lg:px-15 bg-white lg:w-1/3'>
              <Image src={book} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-semibold py-2 text-rose-700 lg:text-xl'>Backend Development</h3>
              <p className='py-2 leading-8 text-gray-800'>I can manage the backend using many frameworks & services.</p>
              <h4 className="text-md font-semibold py-2 text-rose-700">What I Use</h4>
              <p className='text-gray-800 py-1'> Node.js</p>
              <p className='text-gray-800 py-1'>Express.js</p>
              <p className='text-gray-800 py-1'>Firebase & MongoDB</p>
            </div>
            <div className='mb-5 text-center shadow-xl p-10 rounded-lg lg:text-lg lg:px-15 bg-white lg:w-1/3'>
              <Image src={thumb} width={100} height={100} className='mx-auto' />
              <h3 className='text-lg font-semibold py-2 text-rose-700 lg:text-xl'>Tireless Work</h3>
              <p className='py-2 leading-8 text-gray-800'>Having dropped out of college to teach myself software development, I know what it takes to self-motivate and work efficiently.</p>
              <h4 className="text-md font-semibold py-2 text-rose-700">What I Am</h4>
              <p className='text-gray-800 py-1'>Fast Learner</p>
              <p className='text-gray-800 py-1'>Hard Worker</p>
              <p className='text-gray-800 py-1'>Enthusiastic & Cooperative</p>
            </div>
          </div>
        </section>
        <section className='px-10 md:px-20 lg:px-40'>
          <div>
            <h3 className='text-2xl py-5 font-semibold text-transparent 
          bg-clip-text bg-gradient-to-b from-rose-700 to-violet-500 flex justify-center md:text-3xl lg:text-4xl'>My Projects</h3>
          </div>
        </section>
        <section className='px-10 md:px-20 pb-7 lg:px-40 bg-gradient-to-br from-rose-50 to-white'>
          <div>
            <h3 className='text-2xl py-5 font-semibold text-transparent 
          bg-clip-text bg-gradient-to-b from-rose-700 to-violet-500 flex justify-center md:text-3xl lg:text-4xl'>About Me</h3>
            <div className='flex flex-col items-center gap-4 text-gray-800 text-md lg:text-lg'>
              <p className='text-center'>My name is Logan, I'm 21 years old, and I'm a self-taught fullstack web developer looking for his first job in the field.</p>
              <p className='text-center'>After spending 4 years in college without a real direction, I came to the conclusion that dropping out and pursuing a career in a field which I enjoyed a lot was probably the ideal choice for me.</p>
              <p className='text-center'>I've spent the past year (through many resources, including the infamous <a className='text-rose-400' href='https://www.theodinproject.com/paths/full-stack-javascript?'>Odin Project Curriculum</a>), building projects and working hard to improve my programming skills.</p>
            </div>

            <p className='text-center text-lg font-semibold text-gray-800 my-10 lg:text-xl'>To the point where I'm confident that I'm ready for my first job in the field.</p>
            <ul>
              <ol></ol>
            </ul>

          </div>
        </section>
        <section className='bg-white px-10 md:px-20 lg:px-40'>
          <div>
            <h3 className='text-2xl py-5 font-semibold text-transparent 
          bg-clip-text bg-gradient-to-b from-rose-700 to-violet-500 flex justify-center md:text-3xl lg:text-4xl'>Testimonials</h3>
          </div>
        </section>
      </main>
    </div>
  );
}
