import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FaMoon, FaLinkedin, FaGithub, FaYoutube } from 'react-icons/fa'
import profile from '../public/profile.png'
import computer from '../public/computer.png'
import book from '../public/book.png'
import { useState, useEffect } from 'react'


export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "mode-dark" : ""}>
      <Head>
        <title className=''>Logan Robitaille's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main className='bg-white  font-Oxygen  dark:bg-black'>
          <section className=" min-h-screen px-10 md:px-20 lg:px-40">
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-lg text-gray-800'>Logan Robitaille</h1>
              <ul className='flex items-center gap-4'>
                <li className='cursor-pointer text-2xl text-gray-800'><FaMoon className='text-gray-800'onClick={() => {setDarkMode(!darkMode); console.log(darkMode)}}/></li>
                <li><a className='bg-gradient-to-tr from-blue-700 to-indigo-400 text-white px-4 py-2 rounded-md lm-8' href="#">Resume</a></li>
              </ul>
            </nav>
            <div className='flex mx-auto my-5 relative bg-gradient-to-r from-blue-700 to-indigo-400 rounded-full w-60 h-60 border-2 border-white'>

            </div>
            <div className='text-center p-10'>
              <h2 className="text-3xl font-semibold py-2 text-transparent 
            bg-clip-text bg-gradient-to-tr from-blue-700 to-indigo-400 md:text-4xl lg:text-5xl ">Logan Robitaille</h2>
              <h3 className="text-md font-semibold py-2 text-blue-700 md:text-xl lg:text-2xl">Fullstack Junior Developer</h3>
              <p className="text-md pt-2 leading-8 text-gray-800 lg:text-lg">
                Self-taught developer specializing in frontend development.
              </p>
              <p className="text-md mx-auto pb-2 leading-8 text-gray-800 lg:text-lg">
                Well-versed in JavaScript, React.js, Next.js, HTML, CSS, Tailwind CSS, Node.js & Express.js
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-8 text-gray-800'>
              <a><FaLinkedin /></a>
              <a><FaGithub /></a>
            </div>
          </section>
          <section className='px-10 md:px-20 pb-7 lg:px-40 bg-gradient-to-br from-blue-50 to-white'>
            <div className='flex flex-col justify-center'>
              <h3 className='text-2xl py-5 font-semibold text-transparent 
          bg-clip-text bg-gradient-to-tr from-blue-700 to-indigo-400 flex justify-center md:text-3xl lg:text-4xl'>What I bring to the table</h3>
              <p className='text-md py-2 pb-5 leading-8 text-gray-800 text-center lg:text-lg'>
                Paragraph. Paragraph. Paragraph. Paragraph. Paragraph. Paragraph.
                Paragraph. Paragraph. Paragraph. Paragraph. Paragraph. Paragraph.
              </p>
            </div>
            <div className='lg:flex flex-row gap-5 justify-center'>
              <div className='mb-5 text-center shadow-xl p-10 rounded-lg lg:text-lg px-15 bg-white'>
                <Image src={computer} width={100} height={100} className='mx-auto' />
                <h3 className='text-lg font-semibold py-2 text-blue-700 lg:text-xl'>Beautiful Designs</h3>
                <p className='py-2 leading-8 text-gray-800'>Beautiful Designs. Beautiful Designs.
                  Beautiful Designs.</p>
                <h4 className="text-md font-semibold py-2 text-blue-700">What I use</h4>
                <p className='text-gray-800 py-1'> Language</p>
                <p className='text-gray-800 py-1'>Framework</p>
                <p className='text-gray-800 py-1'>Tool</p>
              </div>
              <div className='mb-5 text-center shadow-xl p-10 rounded-lg lg:text-lg px-15 bg-white'>
                <Image src={book} width={100} height={100} className='mx-auto' />
                <h3 className='text-lg font-semibold py-2 text-blue-700 lg:text-xl'>Beautiful Designs</h3>
                <p className='py-2 leading-8 text-gray-800'>Beautiful Designs. Beautiful Designs.
                  Beautiful Designs.</p>
                <h4 className="text-md font-semibold py-2 text-blue-700">What I use</h4>
                <p className='text-gray-800 py-1'> Language</p>
                <p className='text-gray-800 py-1'>Framework</p>
                <p className='text-gray-800 py-1'>Tool</p>
              </div>
              <div className='mb-5 text-center shadow-xl p-10 rounded-lg lg:text-lg px-15 bg-white'>
                <Image src={computer} width={100} height={100} className='mx-auto' />
                <h3 className='text-lg font-semibold py-2 text-blue-700 lg:text-xl'>Beautiful Designs</h3>
                <p className='py-2 leading-8 text-gray-800'>Beautiful Designs. Beautiful Designs.
                  Beautiful Designs.</p>
                <h4 className="text-md font-semibold py-2 text-blue-700">What I use</h4>
                <p className='text-gray-800 py-1'> Language</p>
                <p className='text-gray-800 py-1'>Framework</p>
                <p className='text-gray-800 py-1'>Tool</p>
              </div>
            </div>
          </section>
          <section className='px-10 md:px-20 lg:px-40'>
            <div>
              <h3 className='text-2xl py-5 font-semibold text-transparent 
          bg-clip-text bg-gradient-to-tr from-blue-700 to-indigo-400 flex justify-center md:text-3xl lg:text-4xl'>My Projects</h3>
            </div>
          </section>
        </main>
      </div>
  );
}
